ALTER TABLE queue_table DROP PRIMARY KEY;

ALTER TABLE  `queue_table` ADD  `id` INT NOT NULL AUTO_INCREMENT FIRST ,
ADD PRIMARY KEY (  `id` )

ALTER TABLE  `inbound_rout` ADD  `id` INT NOT NULL AUTO_INCREMENT FIRST ,
ADD PRIMARY KEY (  `id` )